global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    service: "mm-bot"
    env: "staging"

rule_files:
  - "alerts/mm_bot.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'mm_bot'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: app

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
