name: CI (fast)

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_NO_PYTHON_VERSION_WARNING: "1"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Prepare minimal requirements for CI
        shell: bash
        run: |
          if [ -f requirements.txt ]; then
            awk 'BEGIN{IGNORECASE=1}
                 /^bybit-connector/ {next}
                 /^git\+ssh:/        {next}
                 {print}' requirements.txt > requirements_ci.txt
            echo "---- requirements_ci.txt ----"
            cat requirements_ci.txt || true
            echo "-----------------------------"
          fi

      - name: Install deps (CI subset)
        shell: bash
        run: |
          python -m pip install -U pip
          if [ -s requirements_ci.txt ]; then
            pip install -r requirements_ci.txt
          else
            echo "requirements_ci.txt is empty or missing ? skipping pip install"
          fi
          pip list

      - name: Run fast tests
        shell: bash
        run: |
          pytest -q -k "full_stack_validation_e2e or full_stack_validation_json_deterministic"

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs
          path: |
            .pytest_cache/**
            artifacts/**
          if-no-files-found: ignore
