name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      PYTHONPATH: ${{ github.workspace }}
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_NO_PYTHON_VERSION_WARNING: "1"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install minimal deps
        run: |
          python -m pip install -U pip
          pip install "pytest>=7,<9"
          python -V
          pip list

      - name: Run fast tests (verbose)
        run: |
          pytest -vv -s --maxfail=1 -k "full_stack_validation_e2e or full_stack_validation_json_deterministic"

      - name: Always upload pytest logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs
          path: |
            .pytest_cache/**
            artifacts/**
          if-no-files-found: ignore
