name: CI (fast)

on:
  push:
  pull_request:

jobs:
  # ===========================================================================
  # UNIT TESTS: Fast, low memory (~2-3 min)
  # ===========================================================================
  tests-unit:
    name: Unit Tests (fast)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      PYTHONPATH: "${{ github.workspace }}"
      # Test credentials for CI environment (not real keys)
      BYBIT_API_KEY: "test_api_key_for_ci_only"
      BYBIT_API_SECRET: "test_api_secret_for_ci_only"
      STORAGE_PG_PASSWORD: "test_pg_password_for_ci_only"

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true  # Enable Git LFS support if needed
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Prepare minimal requirements for CI
        shell: bash
        run: |
          awk '
            BEGIN{IGNORECASE=1}
            /^bybit-connector/ {next}
            /^mm-orderbook/    {next}
            /^git\+ssh:/       {next}
            {print}
          ' requirements.txt > requirements_ci.txt
          echo "pydantic>=2,<3"           >> requirements_ci.txt
          echo "pydantic-settings>=2,<3"  >> requirements_ci.txt
          echo "pandas>=2,<3"             >> requirements_ci.txt
          cat requirements_ci.txt

      - name: Install deps (CI subset)
        run: |
          python -m pip install -U pip
          pip install -r requirements_ci.txt

      - name: "[DEBUG] Environment and File Structure"
        run: |
          echo "=============================================="
          echo "CI DIAGNOSTIC INFORMATION"
          echo "=============================================="
          echo ""
          echo "--- Current Working Directory ---"
          pwd
          echo ""
          echo "--- Directory Structure (tests/) ---"
          ls -la tests/ || echo "tests/ not found"
          echo ""
          echo "--- tests/fixtures/ Contents ---"
          ls -la tests/fixtures/ || echo "tests/fixtures/ not found"
          echo ""
          echo "--- tests/golden/ Contents ---"
          ls -la tests/golden/ || echo "tests/golden/ not found"
          echo ""
          echo "--- Specific File Checks ---"
          echo "tests/fixtures/audit/chain_ok.jsonl:"
          ls -la tests/fixtures/audit/chain_ok.jsonl || echo "  NOT FOUND"
          echo "tests/golden/EDGE_REPORT_case1.json:"
          ls -la tests/golden/EDGE_REPORT_case1.json || echo "  NOT FOUND"
          echo ""
          echo "--- File Counts ---"
          echo "tests/fixtures/ files: $(find tests/fixtures/ -type f 2>/dev/null | wc -l)"
          echo "tests/golden/ files: $(find tests/golden/ -type f 2>/dev/null | wc -l)"
          echo ""
          echo "--- Python Environment ---"
          python --version
          which python
          echo "PYTHONPATH: $PYTHONPATH"
          echo ""
          echo "=============================================="

      - name: "[DEBUG] Run Single Failing Test"
        continue-on-error: true
        run: |
          echo "=============================================="
          echo "SINGLE TEST DIAGNOSTIC"
          echo "=============================================="
          echo "Running: tests/test_finops_exporter_unit.py"
          python -m pytest tests/test_finops_exporter_unit.py -v --tb=short
          echo "=============================================="

      - name: Run Unit Tests
        # Unit tests: Fast, low memory, use -n 2 for speed
        run: |
          python tools/ci/run_selected_unit.py

  # ===========================================================================
  # E2E TESTS: Slower, higher memory (~20-30 min)
  # ===========================================================================
  tests-e2e:
    name: E2E Tests (integration)
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      PYTHONPATH: "${{ github.workspace }}"
      # Test credentials for CI environment (not real keys)
      BYBIT_API_KEY: "test_api_key_for_ci_only"
      BYBIT_API_SECRET: "test_api_secret_for_ci_only"
      STORAGE_PG_PASSWORD: "test_pg_password_for_ci_only"

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true  # Enable Git LFS support if needed
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Prepare minimal requirements for CI
        shell: bash
        run: |
          awk '
            BEGIN{IGNORECASE=1}
            /^bybit-connector/ {next}
            /^mm-orderbook/    {next}
            /^git\+ssh:/       {next}
            {print}
          ' requirements.txt > requirements_ci.txt
          echo "pydantic>=2,<3"           >> requirements_ci.txt
          echo "pydantic-settings>=2,<3"  >> requirements_ci.txt
          echo "pandas>=2,<3"             >> requirements_ci.txt

      - name: Install deps (CI subset)
        run: |
          python -m pip install -U pip
          pip install -r requirements_ci.txt

      - name: "[DEBUG] Environment and File Structure"
        run: |
          echo "=============================================="
          echo "CI DIAGNOSTIC INFORMATION"
          echo "=============================================="
          echo ""
          echo "--- Current Working Directory ---"
          pwd
          echo ""
          echo "--- Directory Structure (tests/) ---"
          ls -la tests/ || echo "tests/ not found"
          echo ""
          echo "--- tests/fixtures/ Contents ---"
          ls -la tests/fixtures/ || echo "tests/fixtures/ not found"
          echo ""
          echo "--- tests/golden/ Contents ---"
          ls -la tests/golden/ || echo "tests/golden/ not found"
          echo ""
          echo "--- Specific File Checks ---"
          echo "tests/fixtures/audit/chain_ok.jsonl:"
          ls -la tests/fixtures/audit/chain_ok.jsonl || echo "  NOT FOUND"
          echo "tests/golden/EDGE_REPORT_case1.json:"
          ls -la tests/golden/EDGE_REPORT_case1.json || echo "  NOT FOUND"
          echo ""
          echo "--- File Counts ---"
          echo "tests/fixtures/ files: $(find tests/fixtures/ -type f 2>/dev/null | wc -l)"
          echo "tests/golden/ files: $(find tests/golden/ -type f 2>/dev/null | wc -l)"
          echo ""
          echo "--- Python Environment ---"
          python --version
          which python
          echo "PYTHONPATH: $PYTHONPATH"
          echo ""
          echo "=============================================="

      - name: "[DEBUG] Run Single Failing Test"
        continue-on-error: true
        run: |
          echo "=============================================="
          echo "SINGLE TEST DIAGNOSTIC"
          echo "=============================================="
          echo "Running: tests/test_finops_exporter_unit.py"
          python -m pytest tests/test_finops_exporter_unit.py -v --tb=short
          echo "=============================================="

      - name: Run E2E Tests
        # E2E tests: Sequential mode (-n 0) to prevent OOM
        # These tests use heavy fixtures, run them one at a time
        run: |
          python tools/ci/run_selected_e2e.py
