name: CI (fast)

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      PYTHONPATH: "${{ github.workspace }}"
      # Test credentials for CI environment (not real keys)
      BYBIT_API_KEY: "test_api_key_for_ci_only"
      BYBIT_API_SECRET: "test_api_secret_for_ci_only"
      STORAGE_PG_PASSWORD: "test_pg_password_for_ci_only"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: "[DEBUG] Environment Snapshot (Pre-Install)"
        shell: bash
        run: |
          echo "=============================================="
          echo "ENVIRONMENT DIAGNOSTIC SNAPSHOT"
          echo "=============================================="
          echo ""
          echo "--- Working Directory ---"
          pwd
          echo ""
          echo "--- Directory Listing ---"
          ls -la
          echo ""
          echo "--- Python Version ---"
          python --version
          python -c "import sys; print('Executable:', sys.executable); print('Path:', sys.path)"
          echo ""
          echo "--- Pip Version ---"
          pip --version
          echo ""
          echo "--- Environment Variables (sorted) ---"
          env | sort
          echo ""
          echo "--- Disk Space ---"
          df -h .
          echo ""
          echo "=============================================="

      - name: Prepare minimal requirements for CI
        shell: bash
        run: |
          awk '
            BEGIN{IGNORECASE=1}
            /^bybit-connector/ {next}
            /^mm-orderbook/    {next}
            /^git\+ssh:/       {next}
            {print}
          ' requirements.txt > requirements_ci.txt
          echo "pydantic>=2,<3"           >> requirements_ci.txt
          echo "pydantic-settings>=2,<3"  >> requirements_ci.txt
          echo "pandas>=2,<3"             >> requirements_ci.txt
          cat requirements_ci.txt

      - name: Install deps (CI subset)
        run: |
          python -m pip install -U pip
          pip install -r requirements_ci.txt

      - name: "[DEBUG] Environment Snapshot (Post-Install)"
        shell: bash
        run: |
          echo "=============================================="
          echo "POST-INSTALL DIAGNOSTIC SNAPSHOT"
          echo "=============================================="
          echo ""
          echo "--- Installed Packages (pip freeze) ---"
          pip freeze
          echo ""
          echo "--- Pytest Version ---"
          pip show pytest pytest-xdist pytest-timeout || echo "pytest not installed"
          echo ""
          echo "--- PYTHONPATH ---"
          echo "PYTHONPATH=${PYTHONPATH:-<not set>}"
          echo ""
          echo "=============================================="

      - name: "[DEBUG] Run Isolated Whitelist Test"
        continue-on-error: true
        run: |
          echo "=============================================="
          echo "ISOLATED WHITELIST TEST DIAGNOSTIC"
          echo "=============================================="
          python tools/ci/debug_whitelist_test.py
          echo "=============================================="

      - name: Run fast tests (verbose)
        run: |
          pytest -vv -s --maxfail=1 tests/e2e/test_full_stack_validation.py
