name: Dry-Run

on:
  workflow_dispatch:
    inputs:
      iterations:
        description: 'Iterations (windows)'
        type: number
        required: false
        default: 12
      symbols:
        description: 'Symbols (comma-separated)'
        type: string
        required: false
        default: 'BTCUSDT,ETHUSDT'

jobs:
  dryrun:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      SOAK_ARTIFACTS_DIR: artifacts/soak/latest
      SOAK_OUT_DIR: artifacts/soak/latest
      ITERATIONS: ${{ inputs.iterations }}
      SYMBOLS: ${{ inputs.symbols }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint - forbid base requirements.txt in CI
        shell: bash
        run: |
          set -euo pipefail
          # Ищем только реальные команды, исключая echo/quotes и комментарии
          if git grep -nP '^[ \t\-]*[^"#\n]*\bpip([ \t]+|-3[ \t]+)?install[^|#\n]*\B-r[ \t]+requirements\.txt\b' .github/workflows | tee /dev/stderr; then
            echo "::error::Found forbidden 'pip install -r requirements.txt' in CI workflows. Use requirements_ci.txt or extras." >&2
            exit 1
          fi

      - name: Show event and inputs
        shell: bash
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "iterations=${ITERATIONS}"
          echo "symbols=${SYMBOLS}"

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (best-effort)
        shell: bash
        run: |
          python -m pip install -U pip || true
          pip install -e . || true
          pip install -q -r requirements_ci.txt || true

      - name: Shadow export (smoke)
        shell: bash
        run: |
          mkdir -p artifacts/shadow/latest
          echo '{"ok": true, "ts": "'$(date -u +%FT%TZ)'"}' > artifacts/shadow/latest/POST_SHADOW_SNAPSHOT.json
          ls -la artifacts/shadow/latest

      - name: Dry-Run validation (smoke)
        shell: bash
        run: |
          echo "Running dryrun smoke..."
          mkdir -p artifacts/reports
          echo "# DRYRUN SMOKE OK" > artifacts/reports/DRYRUN_ACCURACY_REPORT.md
          echo '{"status":"SMOKE"}' > artifacts/reports/DRYRUN_ACCURACY_REPORT.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dryrun-artifacts
          path: |
            artifacts/**
